// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cakenuy.Data;

#nullable disable

namespace cakenuy.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260103084716_AddOrderTables")]
    partial class AddOrderTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("cakenuy.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkShift")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("cakenuy.Models.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Cake",
                            CreatedAt = new DateTime(2026, 1, 3, 15, 47, 15, 984, DateTimeKind.Local).AddTicks(7621),
                            Description = "Kue coklat berlapis dengan frosting coklat krim yang lembut, dihiasi chocolate shavings dan buah berry segar.",
                            ImageUrl = "/images/chocolate_cake.png",
                            IsAvailable = true,
                            Name = "🍫 Chocolate Delight",
                            Price = 180000m,
                            UpdatedAt = new DateTime(2026, 1, 3, 15, 47, 15, 984, DateTimeKind.Local).AddTicks(7622)
                        },
                        new
                        {
                            Id = 2,
                            Category = "Cake",
                            CreatedAt = new DateTime(2026, 1, 3, 15, 47, 15, 984, DateTimeKind.Local).AddTicks(7628),
                            Description = "Kue strawberry segar dengan krim lembut dan strawberry premium di setiap lapisan. Sempurna untuk perayaan spesial.",
                            ImageUrl = "/images/strawberry_cake.png",
                            IsAvailable = true,
                            Name = "🍓 Strawberry Bliss",
                            Price = 200000m,
                            UpdatedAt = new DateTime(2026, 1, 3, 15, 47, 15, 984, DateTimeKind.Local).AddTicks(7629)
                        },
                        new
                        {
                            Id = 3,
                            Category = "Cupcake",
                            CreatedAt = new DateTime(2026, 1, 3, 15, 47, 15, 984, DateTimeKind.Local).AddTicks(7634),
                            Description = "Set 6 cupcake vanilla dengan frosting pink yang manis, ditaburi sprinkles warna-warni. Cocok untuk acara kecil.",
                            ImageUrl = "/images/vanilla_cupcake.png",
                            IsAvailable = true,
                            Name = "🧁 Vanilla Dream Cupcakes",
                            Price = 85000m,
                            UpdatedAt = new DateTime(2026, 1, 3, 15, 47, 15, 984, DateTimeKind.Local).AddTicks(7635)
                        },
                        new
                        {
                            Id = 4,
                            Category = "Cake",
                            CreatedAt = new DateTime(2026, 1, 3, 15, 47, 15, 984, DateTimeKind.Local).AddTicks(7640),
                            Description = "Kue red velvet klasik dengan cream cheese frosting yang creamy. Warna merah menawan dengan rasa yang tak terlupakan.",
                            ImageUrl = "/images/red_velvet_cake.png",
                            IsAvailable = true,
                            Name = "❤️ Red Velvet Romance",
                            Price = 195000m,
                            UpdatedAt = new DateTime(2026, 1, 3, 15, 47, 15, 984, DateTimeKind.Local).AddTicks(7641)
                        },
                        new
                        {
                            Id = 5,
                            Category = "Cake",
                            CreatedAt = new DateTime(2026, 1, 3, 15, 47, 15, 984, DateTimeKind.Local).AddTicks(7646),
                            Description = "Kue matcha premium dengan krim putih lembut, ditaburi bubuk matcha pilihan. Perpaduan rasa manis dan pahit yang sempurna.",
                            ImageUrl = "/images/matcha_cake.png",
                            IsAvailable = true,
                            Name = "🍵 Matcha Heaven",
                            Price = 175000m,
                            UpdatedAt = new DateTime(2026, 1, 3, 15, 47, 15, 984, DateTimeKind.Local).AddTicks(7647)
                        },
                        new
                        {
                            Id = 6,
                            Category = "Cake",
                            CreatedAt = new DateTime(2026, 1, 3, 15, 47, 15, 984, DateTimeKind.Local).AddTicks(7651),
                            Description = "Tiramisu Italia autentik dengan ladyfinger yang direndam kopi espresso dan mascarpone cream. Ditaburi cocoa powder premium.",
                            ImageUrl = "/images/tiramisu_cake.png",
                            IsAvailable = true,
                            Name = "☕ Tiramisu Classic",
                            Price = 185000m,
                            UpdatedAt = new DateTime(2026, 1, 3, 15, 47, 15, 984, DateTimeKind.Local).AddTicks(7652)
                        });
                });

            modelBuilder.Entity("cakenuy.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("DeliveryAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OrderDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("ServiceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("cakenuy.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MenuItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MenuItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("cakenuy.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "bg-success",
                            CreatedAt = new DateTime(2026, 1, 3, 15, 47, 15, 984, DateTimeKind.Local).AddTicks(7922),
                            Description = "Makan di tempat dengan suasana nyaman dan pelayanan langsung dari staff kami",
                            Icon = "🍽️",
                            IsActive = true,
                            Name = "Dine In",
                            SortOrder = 1,
                            UpdatedAt = new DateTime(2026, 1, 3, 15, 47, 15, 984, DateTimeKind.Local).AddTicks(7923)
                        },
                        new
                        {
                            Id = 2,
                            Color = "bg-warning",
                            CreatedAt = new DateTime(2026, 1, 3, 15, 47, 15, 984, DateTimeKind.Local).AddTicks(7929),
                            Description = "Pesan dan ambil langsung di toko, praktis untuk dibawa pulang",
                            Icon = "🥡",
                            IsActive = true,
                            Name = "Take Away",
                            SortOrder = 2,
                            UpdatedAt = new DateTime(2026, 1, 3, 15, 47, 15, 984, DateTimeKind.Local).AddTicks(7930)
                        },
                        new
                        {
                            Id = 3,
                            Color = "bg-info",
                            CreatedAt = new DateTime(2026, 1, 3, 15, 47, 15, 984, DateTimeKind.Local).AddTicks(7935),
                            Description = "Pesan online dan kami antar langsung ke alamat Anda",
                            Icon = "🚚",
                            IsActive = true,
                            Name = "Delivery Order",
                            SortOrder = 3,
                            UpdatedAt = new DateTime(2026, 1, 3, 15, 47, 15, 984, DateTimeKind.Local).AddTicks(7936)
                        });
                });

            modelBuilder.Entity("cakenuy.Models.Order", b =>
                {
                    b.HasOne("cakenuy.Models.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Service");
                });

            modelBuilder.Entity("cakenuy.Models.OrderItem", b =>
                {
                    b.HasOne("cakenuy.Models.MenuItem", "MenuItem")
                        .WithMany()
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("cakenuy.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuItem");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("cakenuy.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
